# Generated by Django 5.1.4 on 2024-12-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('active', 'Используется'), ('inactive', 'В запасе'), ('broken', 'Сломан')], default='inactive', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='manager.user')),
            ],
        ),
    ]
