# Generated by Django 5.1.6 on 2025-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_purchase_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='action',
            field=models.CharField(blank=True, choices=[('drop', 'Списать оборудование'), ('request', 'Запросить оборудование')], default='drop', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.CharField(choices=[('bought', 'Куплено'), ('delivered', 'Доставлено')], default='bought', max_length=20),
        ),
    ]
