# Generated by Django 5.1.6 on 2025-02-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_application_action_alter_application_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='id',
            new_name='ID',
        ),
    ]
