# Generated by Django 5.1.6 on 2025-02-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_id_application_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='ID',
            new_name='ident',
        ),
    ]
