# Generated by Django 5.1.6 on 2025-02-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_id_application_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('active', 'Используется'), ('inactive', 'В запасе'), ('broken', 'Сломан')], default='inactive', max_length=8),
        ),
    ]
