# Generated by Django 5.1.6 on 2025-02-08 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_application_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purcahses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
