# Generated by Django 5.1.6 on 2025-02-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_purchase_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('seen', 'Рассмотрено'), ('unseen', 'Не рассмотрено')], default='unseen', max_length=8),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.CharField(choices=[('bought', 'Куплено'), ('delivered', 'Доставлено'), ('waiting', 'Ожидается')], default='waiting', max_length=20),
        ),
    ]
