# Generated by Django 5.1.6 on 2025-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_purchase_distributor_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='ident',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='distributor',
            field=models.CharField(choices=[('RosSportNadzor', 'РосСпротНадзор'), ('SportCenter', 'СпортЦентр'), ('Sportbeg', 'СпортБег')], max_length=20),
        ),
    ]
